### ISSUE TITLE
Easy install with conda didn't locate packages

### ISSUE THREAD

**Issue by Rene-Hoover** [Arkadiy-Garber/FeGenie#16]
Hi. I'm trying to install FeGenie with conda (v4.8.3) but when I run the  first command line for the conda install I get the following error messages:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package clone
E: Unable to locate package https://github.com/Arkadiy-Garber
E: Couldn't find any package by glob 'https://github.com/Arkadiy-Garber'
E: Couldn't find any package by regex 'https://github.com/Arkadiy-Garber'
```
I'm running Ubuntu 18.04.4 in case that helps.

**Comment by Arkadiy-Garber** [comment]
Hi Rene,

Thanks for using FeGenie! Sorry that you're having issues getting it installed. I actually haven's seen this error before. You are getting this error after running `git clone https://github.com/Arkadiy-Garber/FeGenie.git`?

Unfortunately, I am not quite sure how to troubleshoot this. I'll look into possible causes.
In the meantime, perhaps you can try downloading the repository directly from FeGenie's GitHub page (see attached). Once you download it, unzip the repository, and proceed with `cd FeGenie` command of the Easy Installation.

Let me know if downloading the repo zip file directly from the website solves this issue for you.

<img width="1660" alt="Screen Shot 2020-08-04 at 12 36 41 AM" src="https://user-images.githubusercontent.com/30564055/89253570-ff450b80-d5ea-11ea-96fb-592ac51f341f.png">

**Comment by Rene-Hoover** [comment]
Thanks for the quick reply! Downloading and extracting the zip file then proceeding with the installation worked.

**Comment by Arkadiy-Garber** [comment]
Great, glad that worked for you!
