### ISSUE TITLE
Option to output prodigal nucleotide file?

### ISSUE THREAD

**Issue by ngilber3** [Arkadiy-Garber/FeGenie#4]
Hello, I've used your tool and it works great! I was wondering if you could add an option to output a nucleotide fasta file, similar to the proteins.faa file created during the Prodigal ORF searching. I would like to do some metatranscriptome mappings to the hits, and so this option would be quite useful. Thanks!

**Comment by Arkadiy-Garber** [comment]
Hey there, thanks for using FeGenie! Sure thing, I can definitely add that as an additional output. I am about to release an updated version of the software, and will have that as an additional output.

Cheers,
Arkadiy

**Comment by Arkadiy-Garber** [comment]
Ok, new version is up. The nucleotide fasta file is written to the same directory that the proteins.faa files are written to. The nucleotide fasta file is named proteins.ffn

Let me know if there are any other issues!

Thanks,
Arkadiy

**Comment by ngilber3** [comment]
This is great! Thanks so much!
