### ISSUE TITLE
geneSummary output protein sequence EMPTY 

### ISSUE THREAD

**Issue by ckeuschn** [Arkadiy-Garber/FeGenie#45]
Hi, 

I have several hits in the geneSummary.csv file witn EMPTY in the protein sequence column. What does that mean? I provided ORFs to analyse but am unsure now if I can use the results. 

iron_oxidation,protein-sequences.faa,713031,sulfocyanin,48.8,45.4,3638,0,0,0,MSVRTSTSVALSVGLGLSLVGGNALTPASAASSRYISYNAHNHTAKIILIGALNNSNQGMNFDGYANGKAIFTVPLGTKVTVAYSDGASKPHSAEIAPWSASIPAAAVTPAFKGAASADYANGSEKGDPISVFTFTASKAGKYRIMCGVTAHAILGMWDVLQVSKSAKVATLN
iron_oxidation,protein-sequences.faa,207671,Cyc2_repCluster2,298.9,27.8,3639,1,0,0,EMPTY
iron_oxidation,protein-sequences.faa,438947,Cyc2_repCluster2,333.9,27.8,3640,1,0,0,EMPTY

Thank you!!

**Comment by Arkadiy-Garber** [comment]
Hi, thanks for your interest in FeGenie! That is a bug that I have been meaning to fix. In this case, "EMPTY" just means that there was some dictionary key within FeGenie's script that had a formatting issue.

In any case, the results are valid in that you do have Cyc2_repCluster2 in your dataset. It's just that FeGenie was unable to retrieve the protein sequence to put in the summary CSV. But you should still be able to find that sequence if you look manually.

Hope this helps!
Arkadiy

**Comment by ckeuschn** [comment]
Thanks for the swift response! Great, yes I can find the sequences otherwise if needed. Great tool, hope you keep improving that!! 
Cheers
Christoph
