### ISSUE TITLE
Error Syntax warning and location

### ISSUE THREAD

**Issue by anestiskos** [Arkadiy-Garber/FeGenie#48]
Hi, 
I am encountering the following error when I am trying to run the software. Any ideas on how to resolve it? 

<img width="646" alt="FeGENIE" src="https://github.com/Arkadiy-Garber/FeGenie/assets/174715672/c40888f6-c80a-4bce-9075-597460ccf8f7">

**Comment by Arkadiy-Garber** [comment]
I see the issue is closed, but wanted to confirm that the issue is resolved.

from the errors above, it looks like the conda installation did not work. Were you able to get this issue resolved?

Thanks,
Arkadiy

**Comment by anestiskos** [comment]
Hi, 

I tried to install without conda, and I was constantly getting this error. In the end, I used conda and I managed to install it and make it work. That's why I closed the issue. 

Thank you for your answer!
