### ISSUE TITLE
An error with FeGenie installed without conda (hmm path problem)

### ISSUE THREAD

**Issue by ilnamkang** [Arkadiy-Garber/FeGenie#7]
Hi,

I've encountered an error during running FeGenie installed without conda.

The error message is as below.

#######
Traceback (most recent call last):
  File "./FeGenie.py", line 458, in main
    test = open(bits)
FileNotFoundError: [Errno 2] No such file or directory: '/HMM-bitcutoffs.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./FeGenie.py", line 1984, in <module>
    main()
  File "./FeGenie.py", line 466, in main
    location = allButTheLast(location, "/")
#######

This error can be solved by manually setting a path to "iron_hmms".
$ export iron_hmms=/path_to/FeGenie/hmms/iron/

Do I have to set the hmm path for FeGenie installed without conda?

Thanks.

**Comment by Arkadiy-Garber** [comment]
Hi! Thanks for bringing this issue to my attention. Did you by chance put the FeGenie repository in your $PATH? This is a requirement for FeGenie. If the $PATH to FeGenie.py is set up in your bash profile, then FeGenie will be able to locate the hmm path without you having to run `export iron_hmms=/path_to/FeGenie/hmms/iron/`.

I will make this requirement clear in the README.

Let me know if you continue to have issues, or have any questions

Thanks for using!
Arkadiy

**Comment by ilnamkang** [comment]
Hi,

Actually, that was the first approach I've tried.

$ cd FeGenie
$ export PATH=$PATH:$(pwd)

But, it didn't work for me.

Anyway, thank you for a great tool. FeGenie helped a lot for me to find putative iron reducing genes in my bacterial genomes.

**Comment by Arkadiy-Garber** [comment]
Ah, gotcha. Sorry, it looks like this was actually a minor bug in the script causing this. I just uploaded the fixed version.

Thanks for using. Glad that FeGenie has been useful to you!
Arkadiy

**Comment by ilnamkang** [comment]
Thanks for a quick fix.

Now it works without running export iron_hmms~~.

Ilnam

**Comment by Arkadiy-Garber** [comment]
That's great. Thanks!
